### PR TITLE
Noncentral distributions

### PR DESCRIPTION
**Pull request by jdeenichin**
## Proposed changes

Added noncentral Beta, ChiSquared, F and t distributions.

## Types of changes

*Put an `x` in the boxes that apply or remove the lines that don't.*

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

*Put an `x` in the boxes that apply or remove the lines that don't. This is a reminder of what we are going to look for before merging your code.*

- [ ] I have added unit tests and **all** tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added documentation where necessary
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jdeenichin** [comment]
Hmm, everything worked fine on my machine yesterday, I'll try to find what the problem is this evening.

**Comment by RaphaelS1** [comment]
You need to run `devtools::document()` to add the classes to the 'collate' field in the description file, then it should run properly

**Comment by RaphaelS1** [comment]
It's failing because `StudentTNoncentral` is not being documentated due to missing parameters in the template, namely:

```R
#' @templateVar params
#' @templateVar pdfpmf
#' @templateVar pdfpmfeq
#' @templateVar paramsupport
```

Would you mind going back and filling these in? Also could you please change `non-centrality parameter` in the template to `location` to be more consistent with other distributions (although in the `ParameterSet` description I think using ncp is fine)

**Comment by jdeenichin** [comment]
This is what I expected but `FDistributionNoncentral` and `BetaNoncentral` don't have any of these parameters as well, however documentation is still created - this is what confuses me the most. Yes, I will change `non-centrality parameter` to `location`, my bad on this one.

**Comment by RaphaelS1** [comment]
That's strange... but they should have that documentation too so can you please add it for all of them

**Comment by RaphaelS1** [comment]
I can clearly see an error when running `devtools::document()` so I'm sure the problem is something to do with documentation

**Comment by jdeenichin** [comment]
I will try that today and hopefully it works. Thanks a lot!

**Comment by jdeenichin** [comment]
I completed the documentation for all 4 noncentral distributions and after I was done with all 4, I ran `devtools::document()`. The output I got was:
```Updating distr6 documentation
Writing NAMESPACE
Loading distr6

-----------------------------
	distr6 v1.1.1

Get started:	?distr6
Changelog:	distr6News()
-----------------------------

Error in cat(distsupport) : object 'distsupport' not found
Writing NAMESPACE
Error in gsub("\n", "\r\n", contents, fixed = TRUE) : 
  input string 1 is invalid UTF-8
```

Again, the 4 `.R` scripts and 3 `.Rd` files are updated, as expected, but `StudentTNoncentral.Rd` is not created. I can't figure out why it behaves differently from the other distributions. All ideas are greatly appreciated!

**Comment by RaphaelS1** [comment]
The template variable `distsupport` was missing from non-central Beta, I've fixed this now and will finish off the PR. Thanks for all your work on this!

**Comment by jdeenichin** [comment]
Thanks for spotting this, I was so focused on finding an issue with the t distribution that I completely missed it!

**Pull request merged**
