### PR TITLE
if/else fix

### PR DESCRIPTION
**Pull request by jdeenichin**
Might have worked before (in which case reject request) but mock examples with same structure (containing `else(logical statement)`) didn't work for me. If the variable 'bound' can be something other than Boolean in future releases (eg bound from one side only) can use `else if (!bound)` instead.

### CODE REVIEW

**Comment by RaphaelS1** [comment]
Hey Jordan, what mock examples are you referring to? As far as I can see the changes edit the if/else statement by removing the redundant `else if` to `else` which is okay but where is it failing?

**Comment by jdeenichin** [comment]
I believe there wasn't a redundant `else if` but rather `else (logical statement)`. I tried the following:
`test <- function(x){
  if (x >= 0)
    print('non-negative')
  else (x < 0)
    print('negative')
}`
where the output of `test(5)` should be "non-negative" but it actually prints both "non-negative" and "negative". Hence, the need for either `else if (logical statement)` or `else` not followed by a logical.

**Comment by RaphaelS1** [comment]
Sorry was looking on mobile before, I see I was missing `if` now, which wasn't needed anyway, thank you :)

**Comment by RaphaelS1** [comment]
I don't fully understand why it worked before... anyway, pulled across, thanks!

**Pull request merged**
